version: "3"
# More info:
# https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
# https://github.com/coredns/coredns
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'America/Denver'
      PIHOLE_DNS_: '${HOST_IP}#1053;${HOST_IP}#1053' #At the time of making this, Pi-hole expected 2 IPs here.
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: always
  dns_forwarder:
    image: "coredns/coredns"
    ports:
            - "1053:1053/udp"
            - "1053:1053"
    volumes:
            - "/etc/coredns/:/etc/coredns/"
    command: -conf /etc/coredns/coreconfig-up -dns.port 1053
    restart: always
    container_name: coredns_up
  dns_listener:
    image: "coredns/coredns"
    ports:
            - "853:853"
    volumes:
            - "/etc/coredns/:/etc/coredns/"
            - "/etc/letsencrypt/:/etc/letsencrypt/"
    command: -conf /etc/coredns/coreconfig-down
    restart: always
    container_name: coredns_down
